### ISSUE TITLE
hello, when I ran AFL fuzz a demo program, the stoch-fuzz didn't respond.

### ISSUE THREAD

**Issue by bufferflyfly** [ZhangZhuoSJTU/StochFuzz#3]
hello, when I ran AFL fuzz a demo program, the stoch-fuzz didn't respond. It keep stopping at “phantom file is create, please execute afldemo.phantom to communicate with the daemon”

**Comment by ZhangZhuoSJTU** [comment]
Closed since the issue is not active for months. Please kindly reopen it if the issue remains in the code base.
