### ISSUE TITLE
Issue in `glib` build

### ISSUE THREAD

**Issue by Silipwn** [ZhangZhuoSJTU/StochFuzz#4]
While trying to build dependencies using the `build.sh`, it turns out the `glib` build fails.
Using the latest commit on `master` and the OS is Ubuntu 18 LTS.

**Comment by ZhangZhuoSJTU** [comment]
Hi @Silipwn , thanks for reporting the issue. Would you mind pasting the build log of glib, especially for the error messages?

**Comment by Silipwn** [comment]
Yeah sure, sharing the `meson.log` from the glib build.
```
Build started at 2021-11-12T22:40:14.933175
 Main binary: /usr/bin/python3
 Python system: Linux
 The Meson build system
 Version: 0.45.1
 Source dir: /home/vagrant/StochFuzz/glib
 Build dir: /home/vagrant/StochFuzz/glib/_build
 Build type: native build

 meson.build:237:14: ERROR: Expecting eol got id.
 if vs_crt_opt in ['mdd', 'mtd']
```

**Comment by ZhangZhuoSJTU** [comment]
Cool. 

I noticed that the version of your `meson` is kind of old. I checked my building system and the corresponding version is `0.60.1`. 

Would you mind trying `pip3 install --upgrade meson` to update your meson? Please let me know if that does not work.

**Comment by Silipwn** [comment]
Works with an upgrade to the latest version of meson. 

Thanks for the help.
